name: banco_digital_flutter
description: Um app de banco digital simples em Flutter.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # Versão mais atual

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logoney.png

flutter_icons:
  android: true
  ios: false
  image_path: "assets/logoney.png"



